sonobuoy-config:
  driver: Job
  plugin-name: datarobot-conformance
  result-format: gojson
  source_url: https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/main/examples/e2e-skeleton/plugin.yaml
  description: An easy to start from project for making K8s aware tests.
spec:
  command:
  - bash
  args: ["-c","go tool test2json ./dr-conformance.test -test.v | tee ${SONOBUOY_RESULTS_DIR}/out.json ; echo ${SONOBUOY_RESULTS_DIR}/out.json > ${SONOBUOY_RESULTS_DIR}/done"]
  image: antonpolyakov/sonobuyo:v0.0.1
  env:
  - name: NS_PREFIX
    value: dr-sonobuyo
  - name: SONOBUOY_PROGRESS_PORT
    value: "8099"
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

