sonobuoy-config:
  driver: Job
  plugin-name: datarobot-conformance
  result-format: gojson
  source_url: https://raw.githubusercontent.com/datarobot/install-prereqchecker/main/plugin.yaml
  description: Tool for checking installation environment for DataRobot conformance
spec:
  command:
    - bash
  args: [ "-c","go tool test2json ./dr-conformance.test -test.v | tee ${SONOBUOY_RESULTS_DIR}/out.json ; echo ${SONOBUOY_RESULTS_DIR}/out.json > ${SONOBUOY_RESULTS_DIR}/done" ]
  image: datarobot/install-prereqchecker:latest
  env:
    - name: MIN_K8S_VERSION
      value: "1.23"
    - name: NS_PREFIX
      value: dr-sonobuyo
    - name: SONOBUOY_PROGRESS_PORT
      value: "8099"
  name: plugin
  resources: { }
  volumeMounts:
    - mountPath: /tmp/sonobuoy/results
      name: results

